# Generated by Django 5.1.4 on 2026-03-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
