# Generated by Django 5.1.4 on 2026-03-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upi', '0007_userprofile_upi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
