# Generated by Django 5.1.4 on 2026-03-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upi', '0010_moneyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyrequest',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='moneyrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='moneyrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
