# Generated by Django 5.1.4 on 2026-03-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upi', '0011_moneyrequest_converted_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='moneyrequest',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
