# Generated by Django 5.1.4 on 2026-03-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upi', '0012_alter_moneyrequest_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyrequest',
            name='currency',
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
