# Generated by Django 5.1.4 on 2026-04-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upi', '0016_supportticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='message',
            new_name='message1',
        ),
        migrations.RenameField(
            model_name='supportticket',
            old_name='subject',
            new_name='subject1',
        ),
    ]
