# Generated by Django 5.1.4 on 2026-04-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upi', '0017_rename_message_supportticket_message1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='message1',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='supportticket',
            old_name='subject1',
            new_name='subject',
        ),
    ]
